### ISSUE TITLE
Primary monitor goes black, works on secondary monitor

### ISSUE THREAD

**Issue by karlc1** [ibhagwan/picom#11]
### Platform

Arch Linux

### GPU, drivers, and screen setup

Nvidia driver version 450.66, dual screen, one 1080p and one 1440p, with the 1080p monitor being the primary one. Configured with xrandr.

`glxinfo -B` output:
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 3072 MB
    Total available memory: 3072 MB
    Currently available dedicated video memory: 2560 MB
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: GeForce GTX 1060 3GB/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 450.66
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6.0 NVIDIA 450.66
OpenGL shading language version string: 4.60 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)

OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 450.66
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20

### Environment

I'm using BSPWM

### picom version

vgit-44b49

### Configuration:
```
// Paste your configuration here
```
I get this issue regardless of configuration

### Steps of reproduction

1. Start picom from terminal

### Expected behavior
I expect to see the settings I made in my picom.conf applied to both of my monitors

### Current Behavior
The settings works great on my seconday monitor, but my primary monitor goes entierly black until i kill picom. 

Edit: I tried to switch which monitor is primary using xrandr, and now it does work on both monitors. However, now the mouse pointer moves very laggy when it's on the secondary monitor (previously primary). The errors logs remain the same.

### Stack trace

❯ picom
[ 09/03/2020 20:52:45.608 x_fence_sync ERROR ] Failed to trigger the fence (X error 136 XSyncBadFence request 134 minor 15 serial 1814)
[ 09/03/2020 20:52:45.608 paint_all ERROR ] x_fence_sync failed, xrender-sync-fence will be disabled from now on.

### Other details

Great job with the fork so far, the rounded corners looks great on the monitor where they are working!

**Comment by ibhagwan** [comment]
Is this issue specific for this fork or picom in general?

**Comment by karlc1** [comment]
I normally use the tryone compton fork without issue, but I have not tried yshui's picom. I can test if I get the same issue with yshui/picom when I get off work if that helps.

**Comment by ibhagwan** [comment]
That would certainly help, picom is a re-written version of compton, obviously I could be wrong but I would assume the issue is related to picom vs compton rather than the rounded corners or blur codes.

You can also try running picom with `picom --config /dev/null` to eliminate any configuration issues (thus also disabling the rounded corners and blur codes).

**Comment by ibhagwan** [comment]
Closed due to inactivity, feel free to reopen if you still need help.
