### ISSUE TITLE
cannot include dwm's system tray from having rounded corners

### ISSUE THREAD

**Issue by faizan-20** [ibhagwan/picom#17]
### Platform
Arch Linux

### Environment
Using DWM window manager

### Expected behavior
No rounded borders on system tray

### Current Behavior
rounded borders on system tray

### Other details
It just looks weird having rounded corners on system tray separately. It also rounds up the top bar but it's easily fixed by excluding 'dwm' but I don't know what to exclude to have system tray behave normally.
![Screenshot_2020-10-31_21-51-28](https://user-images.githubusercontent.com/69417253/97800762-cf2ff780-1c2f-11eb-9369-187472314773.png)

**Comment by ibhagwan** [comment]
I’m not sure how the border width is reported to Xorg but perhaps you can try with manual rule combination such as `round-borders-rule` / `round-borders-exclude`, see [picom.conf.sample](https://github.com/ibhagwan/picom/blob/next/picom.sample.conf) on how to use those.

**Comment by ibhagwan** [comment]
Closed due to inactivity, feel free to reopen if you need help.
