### ISSUE TITLE
no uthash.h (idk what that means)

### ISSUE THREAD

**Issue by orangemn6** [ibhagwan/picom#18]
ubuntu 20.04
i3-gaps
my config:
backend = "glx";

opacity-rule = [ ];

corner-radius = 6.0;
rounded-corners-exclude = [
   # "widthb > 1365 && heightb > 736" # For smart gaps and a non-floating bar
   # "class_g = 'Dunst'"
];

# Add dual-kawase blur
blur-background = true;
blur-background-frame = true;
blur-background-fixed = true;
blur-kern = "3x3box";
blur-method = "gaussian";
blur-strength = 900;
blur-background-exclude = [];

shadow = true;
shadow-radius = 12;
shadow-opacity = 0.25;
shadow-offset-x = -7;
shadow-offset-y = -7;
shadow-exclude = [
    "class_g = 'XAVA'"
];

fading = true;
fade-in-step = 0.2;
fade-out-step = 0.2;
fade-exclude = [ ];
use-damage = false;

When I try to build it says:
Has header "uthash.h" : NO

src/meson.build:35:2: ERROR: Problem encountered: Dependency uthash not found

Please help!!

**Comment by ibhagwan** [comment]
Unfortunately I don’t have Ubuntu ready but generally this means exactly what it says which usually translates to a missing package, try to look online for instructions how to build picom on Ubuntu, I didn’t change anything related to the build process, if you manage to build the original picom you’d be able to build this fork as well.

**Comment by orangemn6** [comment]
I fixed it! I just had to install the uthash-dev package. you should update the dependencies
