### ISSUE TITLE
Bug when using two exclude rules with '&&'

### ISSUE THREAD

**Issue by ajzcole** [ibhagwan/picom#19]
### Platform
Arch Linux x86_64 (on i386)

### GPU, drivers, and screen setup
* Intel HD Graphics 605 (Pentium N5000)
* xf86-video-intel not installed
* Mesa version 20.2.2-2
* Single screen 1366x768

### Environment
Running dwm 6.2

#### picom version
vgit-44b49

#### Extensions
* Shape: Yes
* XRandR: Yes
* Present: Present

#### Drivers
modesetting

### Configuration:
```
# Shadows
shadow = true;
shadow-radius = 15;
shadow-offset-x = -15;
shadow-offset-y = -15;
shadow-opacity = 1;

# Rounded corners
corner-radius = 10;
rounded-corners-exclude = [
	"!class_g = 'dmenu' && !class_g = 'dwm'"
];
```

### Steps of reproduction
Seems to be a 50% chance of working correctly.
1. Start picom
2. To do it again:
```
killall picom
picom & disown
```

### Expected behavior
Only the dwm bar and dmenu windows get rounded corners

### Current Behavior
Occasionally (again, seems to be a 50% chance) the opposite will happen, where dmenu and dwm are unrounded, but everything else is.

**Comment by ttmx** [comment]
I have the same issue, am on Arch aswell, using i3
```
rounded-corners-exclude = [
	"!class_g = 'Spotify' && !class_g = 'discord'"
]
```
I want only spotify and discord to be rounded, but there is about a 50% chance it will work, I have to restart picom multiple times.

**Comment by ibhagwan** [comment]
Ty for letting me know, I'm currently avoiding any fixes to this fork, it's currently being merged into the main picom branch by yshui, you can follow the work [in this pull request](https://github.com/yshui/picom/pull/558).

This will naturally be solved by the merge as they already have this fixed in the `next` branch of yshui's picom.

**Comment by ibhagwan** [comment]
I rebased the code on the latest from the main branch, can you try using the latest code from [next-rebase](https://github.com/ibhagwan/picom/tree/next-rebase)?

**Comment by ajzcole** [comment]
Hey, this is just to let you know that I have seen the message, but I’m about to go away for a few days. I’ll have a chance to test Friday NZST, so I’ll get to it ASAP then.
