### ISSUE TITLE
Memory Leak 🙂

### ISSUE THREAD

**Issue by j-james** [ibhagwan/picom#21]
### Platform
EndeavourOS with Linux 5.9.8

### GPU, drivers, and screen setup
Intel i7-8550U (8) @ 4.000GHz and Intel UHD Graphics 620 on a laptop.

### Environment
I'm using picom alongside bspwm, sxhkd, and xfce4-session.

### picom version
vgit-44b49

### Configuration:
```yaml
corner-radius: 8;
rounded-corners-exclude = [
  "window_type = 'dock'"
];
round-borders = 1;
round-borders-exclude = [
];
round-borders-rule = [
];

shadow = true;
shadow-radius = 10;
shadow-offset-x = -7;
shadow-offset-y = -7;
shadow-exclude = [
  "name = 'Notification'",
  "class_g = 'Wrapper-2.0'",
  "class_g ?= 'Authenticate'",
  "class_g ?= 'polkit-gnome-authentication-agent-1'",
  "_GTK_FRAME_EXTENTS@:c"
];

inactive-opacity = 0.8;
menu-opacity = 1.0
inactive-opacity-override = false;
focus-exclude = [ "class_g = 'Cairo-clock'" ];
opacity-rule = [ "100:class_g = 'Wrapper-2.0'" ];
blur-background = true
blur-kern = "3x3box";
blur-background-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "_GTK_FRAME_EXTENTS@:c"
];

backend = "xrender" // glx is slow on my laptop
vsync = true
mark-wmwin-focused = true;
mark-ovredir-focused = true;
detect-rounded-corners = false;
detect-client-opacity = true;
detect-transient = true
detect-client-leader = true
use-damage = true
log-level = "warn";

wintypes: {
  tooltip = {
    fade = true;
    shadow = true;
    opacity = 0.75;
    focus = true;
    full-shadow = false;
  };
  dock = { shadow = false; }
  dnd = { shadow = false; }
  popup_menu = { opacity = 0.8; }
  dropdown_menu = { opacity = 0.8; }
};
```

### Steps of reproduction
1. Launch this picom fork (I'm using `picom-ibhagwan-git` from the AUR)
2. Launch a cpu-heavy application - Zoom seems to consistently work

### Expected behavior
My RAM should not balloon. 

### Current Behavior
My RAM usage quickly grows (in this case from about 2GB to 8GB in under twenty seconds)
![2020-11-18-090435](https://user-images.githubusercontent.com/35242550/99565754-dfaad680-2980-11eb-9264-5a33650a431c.png)
Interestingly, it doesn't really _look_ like `picom` is eating up all that memory - but killing it instantly fixes any slowdowns and frees up all the memory.

**Comment by ibhagwan** [comment]
Ty for letting me know, I'm currently avoiding any fixes to this fork, it's currently being merged into the main picom branch by yshui, you can follow the work [in this pull request](https://github.com/yshui/picom/pull/558), once it's done it is probably wiser to use the `next` branch of the main fork.

If the memory leak persists after merge I'll take a look into it again.

**Comment by ibhagwan** [comment]
I rebased the code on the latest from the main branch, can you try using the latest code from [next-rebase](https://github.com/ibhagwan/picom/tree/next-rebase)?

**Comment by j-james** [comment]
It seems either much better or completely fixed. I'll have to use it for a longer period of time to see if any long-term issues come up, but Zoom doesn't seem to trigger it anymore.

**Comment by ibhagwan** [comment]
Ty for the update @j-james.

**Comment by j-james** [comment]
Ty for the code @ibhagwan!
