### ISSUE TITLE
[FEATURE REQUEST] individual border colors on each side

### ISSUE THREAD

**Issue by scrouthtv** [ibhagwan/picom#27]
Another thing I found: i3 has an option to draw the one window border where a new window would open in another color.

E. g. if it's set to horizontal tiling, the east border would be in another color than the other three.
This fork redraws the borders by probing the color at (0, 0). But this way it overrides the different-colored border at east.
Maybe this could be improved so that the color is probed for each border individually?

**Comment by ibhagwan** [comment]
You’re correct in your analysis, unfortunately the current GLSL shader code does not support that.

**Comment by scrouthtv** [comment]
Thanks for your response.
