### ISSUE TITLE
Full screen magnification

### ISSUE THREAD

**Issue by Antiquis** [ibhagwan/picom#28]
I am a severely visually impaired user, and I have been wanting to switch to a stand-alone WM with compositor for a long time now, but the total lack of full screen magnification has meant that I and many others in a similar position have been unable to do so.

The maintainers of other Picom forks (and the original) have been unwilling to do this work, and so I was wondering whether you might either implement this into your fork, or create a PR on the main repo?

As you can see in this issue, it is a highly requested feature, yet the maintainer doesn’t seem to see the importance of this.
https://github.com/yshui/picom/issues/43

I would be willing to donate to your project / fork if you would be willing to do this.

Let me know what you think!

**Comment by ibhagwan** [comment]
Hi @Antiquis,

Thank you for approaching regarding this, unfortunately this isn't something I can allocate any time for at the moment.

It does beg the question though, if non-discriminatory full screen magnification is what you're after why not simply use `xrandr`? For example `xrandr --output <your-screen> --scale 1.3x1.3` would "magnify" your screen by 30%.

If `xrandr` alone isn't enough you can always play with `Xft.dpi:` setting in your `~/.xprofile` either globally or per-app (i.e terminal, etc).

Between the above 2 options I believe you can reach a setup that would be sufficiently magnified for both text and graphics.

Hope this helps!

**Comment by Antiquis** [comment]
Hi there,

Thanks for the update on this - much appreciated. No problem, I understand that you must be busy.

Unfortunately adjusting my screen's DPI to achieve a magnification type effect isn't sufficient. I still like to have a normal-looking desktop, but really require full-screen zoom (similar to macOS's implementation).

KDE has a great implementation of this (KMag), but unfortunately that relies on using KWin, which is obviously not ideal for those of us that want to run TWMs.

Thanks anyway man!
