### ISSUE TITLE
Is it possible to whitelist application from being blurred instead of blacklist?

### ISSUE THREAD

**Issue by nonetrix** [ibhagwan/picom#33]
I only want blur effect to be on Awesome and Alacritty but every window seems to be blurred by default taking up resources for no reason 

I was thinking something like this 
```
opacity-include = [
"class_g = 'Alacirtty'",
"class_g = 'Awesome'",
];
```

**Comment by scrouthtv** [comment]
Afaik, @ibhagwan doesn't want to add new features, maybe try reporting this to yshui/picom

**Comment by ibhagwan** [comment]
@scrouthtv is correct, this isn’t the master fork and since most features here will eventually be implemented there it’s better to report there.

**Comment by trk9001** [comment]
Sorry to necro this closed issue, but it seems to me like there is an easy (and sort of documented) way to achieve what @nonetrix wants. As described in the [man page](https://man.archlinux.org/man/picom.1#FORMAT_OF_CONDITIONS), we can logically combine and negate conditions.

So to only blur *kitty* and *Firefox* windows, I would use:

```ini
blur-background-exclude = [          
  "(! class_g = 'kitty') && (! class_g = 'Firefox')"    
];
```

Hope this helps somebody.

**Comment by nonetrix** [comment]
Thanks will try this out

**Comment by nonetrix** [comment]
Seems to be hit and miss doesn't work every time
