### ISSUE TITLE
Picom should exit gracefully but doesn't under --experimental-backends and broken nvidia driver

### ISSUE THREAD

**Issue by Trainraider** [ibhagwan/picom#38]
I'm trying out Bodhi linux but with xfce and i3. My nvidia graphics driver (470) is currently broken. I know, I know, that's not what I'm complaining about here, I need to figure out my nvidia problems on my own. The interesting thing is how picom responds to this situation. My [dotfiles.](https://github.com/Trainraider/dotfiles)

    $ nvidia-smi
    NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.

If I run `picom & disown` picom outputs an error and exits gracefully:

    [ 09/15/2021 22:07:30.620 vsync_opengl_swc_init ERROR ] Failed to load a swap control extension.
    [ 09/15/2021 22:07:30.620 session_init FATAL ERROR ] Failed to initialize the backend

If I run `picom --experimental-backends & disown` Picom runs. All window contents freeze. Any new windows will not display contents Window outlines and rounded corners are visible. Inside the frame is just blurred transparency but no contents. This error message came out once, but Picom continued anyway:

    [ 09/15/2021 22:21:19.108 glx_init ERROR ] Failed to enable vsync. 

It seems to be very much related to [this issue.](https://github.com/yshui/picom/issues/252) except in that case, Picom did exit with the error message. In my mind I figure the `Failed to load a swap control extension...` error message applies to the experimental backends code path but some error checking may have been neglected.

And I just want to mention I compiled picom under -O3 which, you know, *theoretically* doesn't change program behavior.

**Comment by ibhagwan** [comment]
Tysm for the detailed report!

Unfortunately, this doesn't seem like an issue resulting from the code in this fork, namely rounded corners and the dual-kawase blur - most of which was already merged upstream, that means that this issue will have to also be resolved upstream.

As you can see [in the README](https://github.com/ibhagwan/picom#not-included-in-main-branch), there's still code in this fork which isn't included upstream but it's probably not related to your issue.

You can verify what I just wrote by compiling the [main picom fork](https://github.com/yshui/picom/), if this still happens, then that's where you should open this issue.

**Comment by Trainraider** [comment]
Well (unfortunately?) I've fixed my driver issues already and I don't really want to break and fix my system again. I'm sure it'll get fixed by the time the experimental backend becomes just the backend anyway. It might be reproducible running picom with experimental backends in a vm with no vsync support, similar to the issue I linked to.
