### ISSUE TITLE
error in default picom.conf

### ISSUE THREAD

**Issue by Batku** [ibhagwan/picom#39]
"FATAL ERROR" duplicate setting name at line 203 and line 206 (making them comments fixed it) but it should maybe be fixed to be correct by default

**Comment by scrouthtv** [comment]
You mean these lines?

https://github.com/ibhagwan/picom/blob/60eb00ce1b52aee46d343481d0530d5013ab850b/picom.sample.conf#L202-L207

**Comment by Batku** [comment]
> You mean these lines?
> 
> https://github.com/ibhagwan/picom/blob/60eb00ce1b52aee46d343481d0530d5013ab850b/picom.sample.conf#L202-L207

Yes

**Comment by scrouthtv** [comment]
I don't get your point.

The config works fine as-is for me, and the lines aren't duplicate either.

**Comment by ibhagwan** [comment]
These lines wouldn't work if you're using another picom that doesn't support these options, is it possible your installation/compilation failed and you have a different version of picom?

**Comment by scrouthtv** [comment]
Kindly give us the output of `picom --version`

**Comment by Batku** [comment]
> Kindly give us the output of `picom --version`

yeah sorry about not answering, high chance that installation failed, the output of `picom --version` was `vgit-60eb0`

**Comment by ibhagwan** [comment]
> > Kindly give us the output of `picom --version`
> 
> yeah sorry about not answering, high chance that installation failed, the output of `picom --version` was `vgit-60eb0`

You're correct `picom.sample.conf` had duplicates, should be fixed now, tysm!

https://github.com/ibhagwan/picom/commit/c4107bb6cc17773fdc6c48bb2e475ef957513c7a
