### ISSUE TITLE
corner_radius set in wintypes is ignored

### ISSUE THREAD

**Issue by Slickytail** [ibhagwan/picom#4]
### Platform

Kubuntu Desktop 20.02 amd64

### Environment
i3-gaps-resloved, KDE plasma.
### picom version
vgit-44b49

### Configuration:
```
corner-radius = 25.0;
rounded-corners-exclude = [ ];
...
wintypes: {
    tooltip = {
        fade = true;
        shadow = false;
        opacity = 1.00;
        focus = true;
    };
    desktop = {
        shadow = false;
        opacity = 1.0;
        focus = false;
    };
    menu = { shadow = false; };
    dropdown_menu = { shadow = false; };
    popup_menu = { shadow = false; };
    utility = { shadow = false; };
    dock = {
        shadow = false;
        corner_radius = 5;
        opacity = 0.5;
    }
};
```

### Expected behavior
The KDE dock should have 5-pixel radius corners.

### Current Behavior
The KDE dock has 25-pixel radius borders like every other window.

### Other details
The opacity of the dock is correctly set to 0.5, so I know that it's correctly parsing the config and apply the `dock` wintype to the dock window.

**Comment by Philipp-M** [comment]
It should work with a `-` instead of `_` (so `corner-radius` instead of `corner_radius`)
We should probably refactor the names to a unique style to be more consistent...

**Comment by Slickytail** [comment]
Oh, you're totally right. My mistake.
