### ISSUE TITLE
Round border exclude not working with some applications

### ISSUE THREAD

**Issue by PhantomRex123** [ibhagwan/picom#40]
### Platform
ArcoLinux v21.09.11 rolling

### GPU, drivers, and screen setup
Amd, one monitor - xf86-video-amdgpu 

### Environment
XMonad v0.17.0.9 on stack

### picom version
vgit-60eb0

### Configuration:
Due to it being 200+ lines i'll post the main code
```
#################################
#             Corners           #
#################################
# requires: https://github.com/sdhand/compton
corner-radius = 5;
rounded-corners-exclude = [
  #"window_type = 'normal'",
  "class_g = 'Rofi'",
  #"class_g = 'Tint2'",
  "name = 'Notification area'",
  #"class_g = 'kitty'",
  #"class_g = 'Alacritty'",
  "class_g = 'Polybar'",
  "class_g = 'code-oss'",
  "class_g = 'firefox'",
  "class_g = 'Thunderbird'",
  "class_g = 'xmobar'",
  "class_g = 'xterm'"
];
round-borders = 1;
round-borders-exclude = [
  #"class_g = 'TelegramDesktop'",
  "class_g = 'xmobar'",
  "class_g = 'Xterm'"
];
```

### Steps of reproduction
1. Use my configuration on processes like XTerm, XMobar

### Expected behavior
for XMobar to be excluded, while all other applications work properly.

### Current Behavior
All the applications work properly as intended, but XMobar is still rounded 
![2021-11-06_20_24](https://user-images.githubusercontent.com/78041469/140617211-98403d4d-e67f-4b2f-af92-82e2014a688e.png)

### Other details
![2021-11-06_20_01](https://user-images.githubusercontent.com/78041469/140617297-e4a80474-cbc6-41e5-a0ba-7a507c2a0b58.png)

**Comment by ibhagwan** [comment]
Most likely you’re using the wrong `class_g` name, can you run `xprop` and click on your xterm and post the output?

The name you want to be using is the second argument under `WM_NAME` (if I recall correctly).

**Comment by PhantomRex123** [comment]
> Most likely you’re using the wrong `class_g` name, can you run `xprop` and click on your xterm and post the output?
> 
> The name you want to be using is the second argument under `WM_NAME` (if I recall correctly).

Thanks for the quick reply
```
_NET_WM_STRUT(CARDINAL) = 0, 0, 24, 0
_NET_WM_STRUT_PARTIAL(CARDINAL) = 0, 0, 24, 0, 0, 0, 0, 0, 0, 1365, 0, 0
_NET_WM_PID(CARDINAL) = 46801
_NET_WM_DESKTOP(CARDINAL) = 4294967295
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_DOCK
WM_NAME(STRING) = "xmobar"
WM_CLASS(STRING) = "xmobar"
```

**Comment by PhantomRex123** [comment]
So the issue is that its not xterm => XTerm does the job, yet xmobar doesn't work. I'll try and change up my configs and come back

**Comment by ibhagwan** [comment]
> So the issue is that its not xterm => XTerm does the job, yet xmobar doesn't work. I'll try and change up my configs and come back

That’s because `xmobar` doesn’t seem to have the second argument for `WM_ CLASS`, can you try with `class_i` instead of `class_g` or with `name = 'xmobar'`?

**Comment by PhantomRex123** [comment]
thanks, it works. nice tactic!

**Comment by ibhagwan** [comment]
Great!

Out of curiously, which one did you use `class_i` or `name`?

**Comment by PhantomRex123** [comment]
> Great!
> 
> Out of curiously, which one did you use `class_i` or `name`?

I used `name`

**Comment by PhantomRex123** [comment]
![Uploading 2021-11-07_07_40.png…]()

**Comment by PhantomRex123** [comment]
![2021-11-07_07_40](https://user-images.githubusercontent.com/78041469/140632225-9dfea8fa-c4b8-4e00-b12e-26908e43ae09.png)
