### ISSUE TITLE
Unable to exclude dwm systray

### ISSUE THREAD

**Issue by real-99** [ibhagwan/picom#41]
### Platform
Artix Linux (OpenRC)
**Kernel**: 5.10.78-1-lts

### GPU, drivers, and screen setup

Nothing is related to the gpu, but inserting it anyways:
- iGPU **Intel UHD graphics 620** from the **i7-8550u** chip

### Environment
**dwm**, using many patches, the problem is with the `systray` patch.

### picom version
- Output from: `picom --diagnositcs`
```log
**Version:** vgit-c4107
### Extensions:
* Shape: Yes
* XRandR: Yes
* Present: Present

### Misc:
* Use Overlay: Yes
* Config file used: /home/real/.config//picom.conf

### Drivers (inaccurate):
Intel

### Backend: glx
* Driver vendors:
 * GLX: Mesa Project and SGI
 * GL: Intel
* GL renderer: Mesa Intel(R) UHD Graphics 620 (KBL GT2)
* Accelerated: 1

```

### Configuration:
```
# picom.conf -*- the picom compositor config
# requires: picom-ibhagwan-git to work.

# Corners config
corner-radius = 16;
rounded-corners-exclude = [
  "class_g = 'dwm'"
];
round-borders = 1; # Round border to avoid artifacts
```

### Steps of reproduction
Use the config mentionned above

### Expected behavior
All the dwm bar with the systray will be excluded from having rounded corners

### Current Behavior
![21-11-20_15h:18](https://user-images.githubusercontent.com/67875888/142729633-1e5162d8-8847-4bcc-9e13-4befa702483b.png)

### Stack trace
Nothing to mention.

### Other details
Nothing to mention.

**Comment by ibhagwan** [comment]
You most likely have the wrong `class_g`, run `xprop` and click on the tray, post the output here and I can help you get the correct config.

**Comment by Aleph-99** [comment]
Hi again, uhh so, the WM_CLASS attribute changes depending on which icon is picked, that will be tricky...
Any ideas?

**Comment by ibhagwan** [comment]
There must be st least one attribute that doesn’t change, name role, etc.

If you exclude with `class_g`  make sure it’s the second `WM_CLASS` argument, otherwise use `class_i`.

**Comment by Aleph-99** [comment]
What is `class_i` ? What xprop attribute it's for?

**Comment by ibhagwan** [comment]
> What is `class_i` ? What xprop attribute it's for?

`man picom` and you’ll find it everything, this isn’t new for this fork.

`class_i` is the first argument of `WM_CLASS`.

**Comment by Aleph-99** [comment]
Well, the WM_CLASS changes...

**Comment by scrouthtv** [comment]
Maybe try `window_type = 'dock'`:
https://github.com/yshui/picom/blob/next/picom.sample.conf#L150

**Comment by real-99** [comment]
> Maybe try `window_type = 'dock'`: https://github.com/yshui/picom/blob/next/picom.sample.conf#L150

Nope, still nothing

**Comment by kofm** [comment]
did you find any solution? same problem :(

**Comment by real-99** [comment]
Nope, I just removed the systray since I noticed that the icons are blurry and *for some reason*, the icons (discord, screenkey) stay in place even if the apps are pkill'ed

**Comment by kofm** [comment]
You can use this in your exclude 

`"class_g" ?= 'systray'",`
