### ISSUE TITLE
Window-specific blur strength?

### ISSUE THREAD

**Issue by BeanieBen9990** [ibhagwan/picom#43]
Is there a possibility of being able to specify blur strength for specific windows? I use a relatively low blur, which looks great behind terminals and such, but I would like to increase the blur strength only for my screen locker, Slock, so that my text or whatever I'm working on isn't clearly visible behind it. Is there a way to add functionality similar to how you can change which windows get blurred, but for the strength of the blur?

**Comment by ibhagwan** [comment]
There's no `blur-strength` setting for specific windows but the blur highly depedant on the level of transparency of the window, for exmaple, no transparency equals no blur at all, you can try playing with `opacity-rule`:

```conf
opacity-rule = [
  "100:class_g    = 'XTerm'",  # no transparency = no blur
  "80:class_g    = 'URxvt'",   # 20% transparency
];
```

>Is there a way to add functionality similar to how you can change which windows get blurred, but for the strength of the blur?

For that you'd have to open an issue [upstream](https://github.com/yshui/picom).
