### ISSUE TITLE
[Feature Request] Sliding Animation when switching in b/w workspace

### ISSUE THREAD

**Issue by Waishnav** [ibhagwan/picom#47]
### Platform and Environment
I'm on my Arch and using BSPWM as wm

### picom version
vgit-c4107

### Feature Explained
macOS or popOS like sliding animation when switching in b/w workspaces.

@ibhagwan you can look at the following picom fork who has implemented it 
https://github.com/pijulius/picom/commit/b92d4105ea8cc31a22fec64c5241b867b9f92632

**Comment by ibhagwan** [comment]
This fork is almost fully implemented [upstream](https://github.com/yshui/picom), I have no plans on adding new features to this.
