### ISSUE TITLE
`round_borders = 1;` not rounding borders

### ISSUE THREAD

**Issue by AutumnalAntlers** [ibhagwan/picom#7]
### Platform
Gentoo Linux
Commit c212f65c4f1d88ee53e28646e6bc0564055a5cfc

### GPU, drivers, and screen setup
NVidia GTX 2070S, nvidia-drivers 450.57-r1, single monitor

### Environment
BSPWM

### picom version
**Version:** vgit-fd6ff

#### Extensions:

* Shape: Yes
* XRandR: Yes
* Present: Present

#### Misc:

* Use Overlay: No (Another compositor is already running)
* Config file used: /home/eli/.config/picom/picom.conf

#### Drivers (inaccurate):

NVIDIA

### Configuration:
```
experimental-backends = true;
backend = "glx";

corner-radius = 15.0;
rounded-corners-exclude = [
  # "class_g = 'Polybar'",
  "class_g = 'Firefox'",
];

round-borders = 2;
round-borders-rule = [
  # Needed to prevent borders from being cut-off
  # "2:window_type = 'normal'"
];

```

### Steps of reproduction
1. Set round-borders = 1

### Expected behavior
Borders are rounded alongside corners

### Current Behavior
Borders are not rounded (get cut off behind the rounded corner) unless a round-borders-rule is created that applies the rounded borders to all windows.

This feels like it could be a silly configuration error on my part, but I've just spent some time Googling around trying to figure out when border-rounding was added (last April) and why it wasn't working for me until finding the round-borders-rule fix on a whim, showing that it wasn't a technical issue but a configuration one: I've made sure that all my commas, brackets, quotes and semi-colons are in place.

**Comment by AutumnalAntlers** [comment]
> ### Environment
> BSPWM
BSPWM-0.9.9 to be more specific, though I ought to update anyways- Gentoo's package is always slightly behind, as I found out when GCC10 broke compilation.

Setting `round-borders = 1;` and commenting out my `round-borders-rule` causes borders to be cut off again, and was likely the first configuration I tried. Tbh I'm just glad I've got it working, looks absolutely beautiful; thank you for your work c:

**Comment by AutumnalAntlers** [comment]
I had a hunch about it reviewing the commit log before posting, and `git bisect` confirms;
```
c212f65c4f1d88ee53e28646e6bc0564055a5cfc is the first bad commit
commit c212f65c4f1d88ee53e28646e6bc0564055a5cfc
Author: bhagwan <bhagwan@disroot.org>
Date:   Fri Aug 14 11:17:50 2020 -0700

    attempt to fix i3 round_borders rule

 src/backend/gl/gl_common.c | 2 +-
 src/event.c                | 7 +++++++
 src/opengl.c               | 8 ++++----
 src/win.c                  | 4 ++--
 src/win.h                  | 2 +-
 5 files changed, 15 insertions(+), 8 deletions(-)
```  

On any prior commit, BSPWM's rounded borders work perfectly without additional `round-borders-rule`s

**Comment by ibhagwan** [comment]
Oh crap, I didn't realize I actually messed up with that one and it didn't really fix anything :-)

Just reverted that commit, let me know if it works fine for you?

**Comment by AutumnalAntlers** [comment]
I haven't necessarily checked, but given that the prior commit was working fine, I'm sure the reversion was the solution, and am glad to have been of help. I though it was that one, but used git bisect anyways because I'd never used it before! Had a lot of fun reading through the git man pages. Just wish I could offer some insight into solutions for the i3 issue, but that's well over my head, so just thanks again for your work!

On a related side note, yes, it's working just fine again, though the commit was still present in my local repo's `next` branch. Maybe `git-revert` in the future to make an 'undo' commit, despite the messier commit log, to avoid messing with the history of a public-facing repo. I love a clean log myself, but would consider it set in stone once it might have been pulled onto anyone else's machine to avoid hanging commits like these (god forbid it was forked before the history was changed and someone needs to rebase instead of just merging in the reversion commit).

**Comment by ibhagwan** [comment]
Absolutely agree, I’m a bit of a git noob myself, not sure yet which camp I’m at.. the “git as a save button” for code or reorganizing commits to reflect chunks of meaningful changes.

Thank you so much for your help!

**Comment by samox73** [comment]
> You didn’t mention what WM you’re using, if it’s any version of i3 (gaps, etc) then this is expected behavior as i3 does not draw the borders using xcb API thus picom doesn’t realize a border is present and you have to set the rule manually.

How do you set it manually? I am using i3-gaps-rounded-git from the AUR (though not using the rounded feature) and I've been struggling getting it to work.

**Comment by ibhagwan** [comment]
Use `round-borders-rule`, the example below is from [picom.sample.conf](https://github.com/ibhagwan/picom/blob/next/picom.sample.conf):


```
# Specify a list of border width rules, in the format `PIXELS:PATTERN`, 
# Note we don't make any guarantee about possible conflicts with the
# border_width set by the window manager.
#
# example:
#    round-borders-rule = [ "2:class_g = 'URxvt'" ];
#
round-borders-rule = [
  "3:class_g      = 'XTerm'",
  "3:class_g      = 'URxvt'",
  "10:class_g     = 'Alacritty'",
  "15:class_g     = 'Signal'"
];
```
